main: com.spillhuset.OddJob
name: OddJob
version: "0.2"
api-version: "1.16"
softdepend:
  - dynmap

commands:
  auction:
    description: Auction House
    usage: /auction ...
    aliases: [ 'ah' ]
  locks:
    description: Locks Menu
    usage: /locks ...
    aliases: [ 'l' ]
  currency:
    description: EconomyCommand
    usage: /currency <set|add|remove> <player> <amount>
  arena:
    aliases: [ 'a' ]
    description: Arena Menu
    permission: arena
  guild:
    description: Guild Menu
    aliases: [ 'g' ]
  homes:
    description: Homes Menu
    usage: /homes <set|del|list|tp>
    aliases: [ 'h' ]
  invsee:
    description: See another players inventory
    usage: /<command> <Player>
    permission: invsee
  suicide:
    description: Take suicide
    usage: /<command>
  #kill:
  #  description: Kill a given player
  #  usage: /<command> <Player>
  #  permission: essentials.kill
  teleport:
    description: Teleports a player to another player
    usage: /<command> <Player> [OtherPlayer]
    permission: teleport
    aliases: [ 'tp' ]
  tpall:
    description: Teleports all online players to your location
    usage: /<command>
    permission: tpall
  kick:
    description: Kicks a given player from the server
    usage: /<command> <Player> [message]
    permission: kick
  tpa:
    description: Sends a teleport request to a given player
    usage: /<command> <Player>
  tpaccept:
    description: Accepts a teleport request
    usage: /<command>
  tpdeny:
    description: Denies a teleport request
    usage: /<command>
  ban:
    description: Ban a given player
    usage: /<command> <Player> [message]
    permission: ban
  feed:
    description: Feeds a given player
    usage: /<command> [Player]
    permission: feed
  heal:
    description: Heals a given player
    usage: /<command> [Player]
    permission: heal
  give:
    description: Gives an item to a player
  gamemode:
    description: Changes gamemode of given player
    usage: /<command> <GameMode> [Player]
    aliases: [ 'gm' ]
    permission: gamemode
  player:
    description: Access Player settings
    aliases: [ 'p' ]
    permission: player
  warp:
    usage: /<command> <name> [password]
    description: Warp you to a specified location
    aliases: [ 'w' ]
  back:
    usage: /<command>
    description: Teleports back to origin
    permission: back
  freeze:
    usage: /<command>
    description: Toogle freeze a player
    permission: freeze
  death:
    usage: /<command>
    description: Cleans up chests
  backup:
    usage: /<command>
  rollback:
    usage: /<command>
  spawn:
    usage: /<command>
  jail:
    usage: /<command>
  trade:
    usage: /<command>
  shop:
    usage: /<command>
  spawnmob:
    usage: /<command>
    permission: spawnmob
  map:
    usage: /<command>
  sudo:
    usage: /<command> <player> <command_to_execute>
  op:
    usage: /<command> <player>
  deop:
    usage: /<command> <player>
permissions:
  auction:
    default: true
  arena:
    default: true
    children:
      arena.create:
        default: op
  op:
    default: false
  deop:
    default: true
  spawnmob:
    default: op
  tpall:
    default: op
  homes:
    default: true
  homes.*:
    children:
      homes: true
      homes.tp: true
      homes.tp.others: true
      homes.set: true
      homes.set.others: true
      homes.del: true
      homes.del.others: true
      homes.list: true
      homes.list.others: true
  homes.tp:
    default: true
  homes.tp.others:
    default: op
  homes.set:
    default: true
  homes.set.others:
    default: op
  homes.del:
    default: true
  homes.del.others:
    default: op
  homes.list:
    default: true
  homes.list.others:
    default: op
  locks.*:
    children:
      locks.lock: true
      locks.unlock: true
      locks.info: true
      locks.count: true
      locks.list: true
      locks.help: true
      locks.save: false
      locks.load: false
      locks.make: true
      locks.show: true
      locks.make.skeleton: false
  locks.lock:
    default: true
  locks.unlock:
    default: true
  locks.info:
    default: true
  locks.count:
    default: true
  locks.help:
    default: true
  locks.list:
    default: op
  locks.save:
    default: op
  locks.load:
    default: op
  locks.make:
    default: true
  locks.make.skeleton:
    default: op
  locks.show:
    default: true
  player:
    default: true
  warp:
    default: true
    children:
      warp.set:
        default: op
      warp.del:
        default: op
      warp.tp:
        default: true
  guild:
    default: true