main: no.helponline.OddJob
name: OddJob
version: 0.3
api-version: 1.14

commands:
  locks:
    description: Locks plugin
  econ:
    description: EconomyCommand
    usage: /econ <set|add|remove> <player> <amount>
  arena:
  guild:
  homes:
    description: Homes Menu
    usage: /homes <set|del|list|tp>

permissions:
  homes.*:
    children:
      homes.tp: true
      homes.tp.others: true
      homes.set: true
      homes.set.others: true
      homes.del: true
      homes.del.others: true
      homes.list: true
      homes.list.others: true
  homes.tp:
    default: true
  homes.tp.others:
    default: op
  homes.set:
    default: true
  homes.set.others:
    default: op
  homes.del:
    default: true
  homes.del.others:
    default: op
  homes.list:
    default: true
  homes.list.others:
    default: op
  locks.*:
    children:
      locks.lock: true
      locks.unlock: true
      locks.info: true
      locks.count: true
      locks.list: true
      locks.help: true
      locks.save: false
      locks.load: false
      locks.make: true
      locks.show: true
      locks.make.skeleton: false
  locks.lock:
    default: true
  locks.unlock:
    default: true
  locks.info:
    default: true
  locks.count:
    default: true
  locks.help:
    default: true
  locks.list:
    default: op
  locks.save:
    default: op
  locks.load:
    default: op
  locks.make:
    default: true
  locks.make.skeleton:
    default: op
  locks.show:
    default: true